var floatAge, floatDays, intWeeks, floatMonths, intFortnights;
floatAge = parseFloat(prompt("Enter age in years"));
floatDays = parseFloat(floatAge * 365.25);
floatMonths = parseFloat(floatAge * 12);
intWeeks = parseInt(floatDays / 7);
intFortnights = parseInt(floatDays / 14);
alert("Age in years = " + floatAge);
alert("Age in days = " + floatDays);
alert("Age in months = " + floatMonths);
alert("Age in weeks = " + intWeeks);
alert("Age in fortnights = " + intFortnights);
